mergerfs_installer: 'https://github.com/trapexit/mergerfs/releases/download/2.33.1/mergerfs_2.33.1.debian-bullseye_amd64.deb'
snapraid_installer: 'https://github.com/amadvance/snapraid/releases/download/v12.0/snapraid-12.0.tar.gz'
snapraid_runner_git: 'https://github.com/Chronial/snapraid-runner.git' 

mergerfs_mount:
  - path: /mnt/storage

parity_disks:
  - path: /mnt/parity1
    devid: /dev/disk/by-id/ata-WDC_WD140EDGZ-11B1PA0_Y6G29BVC-part1
    fs: ext4
    opts: defaults

data_disks:
  - path: /mnt/disk1
    devid: /dev/disk/by-id/ata-WDC_WD140EDGZ-11B1PA0_Y6G3NK3C-part1
    fs: ext4
    opts: defaults

mergerfs_fstab:
  - source: /mnt/disk*
    path: /mnt/storage
    fs: fuse.mergerfs
    opts: category.create=mfs,defaults,nonempty,use_ino,inodecalc=path-hash,cache.files=off,dropcacheonclose=true,allow_other,minfreespace=50G,func.getattr=newest
