---

- hosts: "{{ host }}"
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'roles/docker_apps/vars/main.yaml'
  vars_prompt:
    - name: host
      prompt: Which host?
      private: no
  tasks:
    - name: Install docker compose file
      template:
        src: roles/docker_apps/files/docker-compose.yaml
        dest: /opt/docker/docker-compose.yaml
        mode: "{{ docker_file_mask }}"
        owner: "{{ secret_username }}"
        validate: docker-compose -f %s config
      when: host == "dockermain"

    - name: Docker Pull
      command: "docker-compose pull"
      args:
        chdir: /opt/docker 

    - name: Docker Update
      command: "docker-compose --profile all up -d"
      args:
        chdir: /opt/docker 

    - name: Docker prune
      command: "docker image prune -af"
