---
roles:
- src: grog.package
- src: geerlingguy.docker
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.pip
- src: geerlingguy.samba
- src: gantsign.oh-my-zsh

collections:
- community.general
- community.docker
