---

- hosts: all
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: basics

# Main Proxmox Host
# -----------------

- hosts: gaara 
  become: true
  vars_files:
    - 'vars/vault.yaml'
  vars:
    docker_compose_version: "v2.2.3"
    backup_server: false
  pre_tasks:
    - name: Remove enterprise repo
      file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Switch to community repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve buster pve-no-subscription'
        state: present
    - name: Apt update
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: geerlingguy.nfs
    - role: geerlingguy.samba
    - role: geerlingguy.docker
    - role: pve 
    - role: zfs

# Backup Proxmox Host
# -----------------

- hosts: tsukuyomi 
  become: true
  vars_files:
    - 'vars/vault.yaml'
  vars:
    backup_server: true
  pre_tasks:
    - name: Remove enterprise repo
      file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Switch to community repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve buster pve-no-subscription'
        state: present
    - name: Apt update
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: zfs

# Main docker host
# ----------------
- hosts: dockermain
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: docker_alpine
    - role: docker_apps
