---

- hosts: dockermain
  vars_files:
    - 'vars/vault.yaml'
  tasks:
    - name: Create openclaw config directory
      file:
        path: /opt/docker/openclaw/config
        state: directory
        mode: "{{ docker_dir_mask }}"
        owner: "{{ secret_username }}"

    - name: Install openclaw config
      template:
        src: roles/docker_apps/files/openclaw/openclaw.json
        dest: /opt/docker/openclaw/config/openclaw.json
        mode: "0600"
        owner: "1000"
        group: "1000"

    - name: Install docker compose file
      template:
        src: roles/docker_apps/files/docker-compose.yaml
        dest: /opt/docker/docker-compose.yaml
        mode: "{{ docker_file_mask }}"
        owner: "{{ secret_username }}"
