- name: Create docker directory on PVE host
  ansible.builtin.file:
    dest: /opt/docker
    state: directory
    owner: "{{ secret_username}}"
    group: "{{ secret_username }}"
    mode: "{{ docker_dir_mask }}" 

- name: Setup docker to run in ZFS
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0775

- name: Install docker-compose for apps on PVE host
  ansible.builtin.template:
    src: files/docker-compose.yaml
    dest: /opt/docker/docker-compose.yaml
    owner: root
    group: root
    mode: 0775
    validate: docker-compose -f %s config
  notify: restart docker
