http:
  routers:
    router-photoprism:
      rule: Host(`photoprism.iyer.app`)
      service: service-photoprism
      middlewares: localip@file
  services:
    service-photoprism:
      loadBalancer:
        servers:
          - url: http://192.168.1.202:2342
