---

- name: restart openclaw gateway
  systemd:
    name: openclaw-gateway
    state: restarted
    daemon_reload: yes

- name: restart claude-max-api-proxy
  systemd:
    name: claude-max-api-proxy
    state: restarted
    daemon_reload: yes
