- name: Create homer directory
  file:
    path: /opt/docker/homer
    state: directory
    owner: "{{ secret_username }}"
    mode: "{{ docker_dir_mask }}"
      
- name: Copy assets
  ansible.posix.synchronize:
    src: files/homer/tools
    dest: /opt/docker/homer

- name: Install config
  template: 
    src: files/homer/config.yml
    dest: /opt/docker/homer/config.yml
    owner: "{{ secret_username }}"
    mode: "{{ docker_dir_mask }}"
